export const starterPlan = {
  name: "Ficha inicial",
  days: [
    {
      name: "Lower 1",
      weekday: 0,
      exercises: [
        {
          name: "Cadeira flexora",
          sets: 3,
          repMin: 8,
          repMax: 12,
          instruction: "tronco levemente a frente",
        },
        {
          name: "Cadeira adutora",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "quadril flexionado",
        },
        {
          name: "Leg press",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: "pes medios/altos",
        },
        {
          name: "Elevacao pelvica",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: null,
        },
        {
          name: "Cadeira extensora",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "quadril estendido",
        },
        {
          name: "Panturrilha maquina",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: null,
        },
      ],
    },
    {
      name: "Upper 1",
      weekday: 1,
      exercises: [
        {
          name: "Supino reto maquina",
          sets: 3,
          repMin: 5,
          repMax: 8,
          instruction: "ou Smith",
        },
        {
          name: "Polia baixa para cima",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "crucifixo inclinado",
        },
        {
          name: "Puxada aberta maquina/barra",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: null,
        },
        {
          name: "T-bar row maquina",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: null,
        },
        {
          name: "Elevacao lateral maquina",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: null,
        },
        {
          name: "Rosca Scott",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: "ou Rosca Martelo padrao encurtado",
        },
        {
          name: "Triceps polia barra W",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: null,
        },
      ],
    },
    {
      name: "Lower 2",
      weekday: 3,
      exercises: [
        {
          name: "Stiff",
          sets: 3,
          repMin: 8,
          repMax: 12,
          instruction: "ou banco romano",
        },
        {
          name: "Cadeira abdutora",
          sets: 2,
          repMin: 12,
          repMax: 20,
          instruction: "quadril flexionado",
        },
        {
          name: "Leg press",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: "pes baixos, assento pra tras",
        },
        {
          name: "Cadeira flexora",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: "quadril neutro",
        },
        {
          name: "Leg press unilateral",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: "ou Bulgaro no Smith, quadril bem flexionado",
        },
        {
          name: "Cadeira extensora",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "quadril flexionado",
        },
        {
          name: "Panturrilha maquina",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: null,
        },
      ],
    },
    {
      name: "Upper 2",
      weekday: 4,
      exercises: [
        {
          name: "Puxada neutra maquina",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: "triangulo",
        },
        {
          name: "Remada",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "ou Cable Shrugs upper back",
        },
        {
          name: "Supino inclinado halteres",
          sets: 3,
          repMin: 6,
          repMax: 10,
          instruction: null,
        },
        {
          name: "Voador",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: "ou crucifixo maquina",
        },
        {
          name: "Elevacao lateral halteres + Elevacao frontal unilateral",
          sets: 2,
          repMin: 10,
          repMax: 15,
          instruction: null,
        },
        {
          name: "Rosca inclinada banco 45",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: "padrao alongado",
        },
        {
          name: "Triceps frances maquina",
          sets: 2,
          repMin: 8,
          repMax: 12,
          instruction: null,
        },
      ],
    },
  ],
};

export async function seedStarterPlan() {
  return { planId: "starter-plan" };
}
